DROP DATABASE herbDB;
CREATE DATABASE herbDB character set UTF8 collate utf8_vietnamese_ci;

CREATE TABLE IF NOT EXISTS `herbDB`.`herb` (
    `herb_No` INT AUTO_INCREMENT,
    `herb_name` VARCHAR(255) NOT NULL,
    `herb_intro` VARCHAR(2047),
    `herb_desc` VARCHAR(2047),
    `herb_attr` VARCHAR(2047),
    `herb_function` VARCHAR(2047),
    `herb_usage` VARCHAR(2047),
    `herb_storage` VARCHAR(2047),
    PRIMARY KEY (`herb_No`)
);

INSERT INTO `herbDB`.`herb` (`herb_name`,
                                `herb_intro`,
                                    `herb_desc`, 
                                        `herb_attr`, 
                                            `herb_function`, 
                                                `herb_usage`, 
                                                    `herb_storage`)
VALUES ("Bạch Phục Linh",
    "Bạch linh được chia thành 4 thứ: Phục linh bì là vỏ ngoài; Xích phục linh là lớp thứ 2 sau vỏ ngoài; Bạch phục linh là phần bên trong màu trắng, thường được sơ chế thành phiến hình khối vuông dẹt", 
        "Bạch linh được chia thành 4 thứ: Phục linh bì là vỏ ngoài; Xích phục linh là lớp thứ 2 sau vỏ ngoài; Bạch phục linh là phần bên trong màu trắng, thường được sơ chế thành phiến hình khối vuông dẹt; Phục thần là những quả thể có lõi gỗ (rễ thông) ở giữa.",
            "Vị ngọt, nhạt, tính bình.",
                "Phục linh bì: Lợi tiểu, trị phù thũng. Xích phục linh: Chữa thấp nhiệt (chướng bụng, viêm bàng quang, tiểu vàng, đái rắt).Bạch phục linh: Chữa ăn uống kém tiêu, đầy chướng, bí tiểu tiện, ho có đờm, ỉa chảy. Phục thần: Trị yếu tim, hoảng sợ, hồi hộp, mất ngủ.",
                    "Ngày 6-12g. Dạng thuốc sắc, hoàn, tán. Phối hợp trong nhiều phương thuốc khác nhau.",
                        ""),
("Cam Thảo",
    "Cam thảo là vị thuốc phổ biến nhất trong Đông y, có vị ngọt, tính bình thường dùng đề điều hòa các vị thuốc. Ngoài ra, bản thân cam thảo là một vị thuốc có khả năng giải độc, tuyên phế trừ ho lao,…", 
        "Cam thảo thuộc dòng cây thân thảo, sống lâu năm, cao từ 30-100cm. Rễ mập mạp, màu vàng. Thân thẳng đứng, gỗ hóa ở gốc, có lông mềm, ngắn. Cuống lá dài khoảng 6 cm, và các hạt rụng sớm, các lá chét có 7 đến 17 mảnh, hình bầu dục hình bầu dục, dài 2 đến 5,5 cm, rộng 1 đến 3 cm, che khuất ở hai bên, tròn ở hai bên. Cụm hoa mọc thành chùm ở nách lá; hoa tím tương đối nhỏ. Quả đậu cong hình lưỡi liềm, dài 3-4cm, rộng 6-8mm, màu nâu đen, có lông dày, chứa 2-8 hạt nhỏ dẹt, màu nâu bóng.",
            "Vị ngọt.",
                "Cam thảo có tác dụng bổ trung ích khí, nhuận phế chỉ khát, hoãn cấp chỉ thống, thanh nhiệt giải độc.",
                    "4 – 12g, có khi dùng đến 50g, tùy mục đích sử dụng, dùng làm thuốc điều hòa lượng thường dùng ít, dùng để giải độc lượng phải nhiều.",
                        "Để nơi khô ráo, cần tránh ẩm, vì rất dễ mốc mọt. Nếu bị mốc mọt, cần sấy bằng hơi nóng (nhiệt độ thấp), để nguội rồi mới cho vào hòm kín, cho vào ngay lúc đang nóng sẽ bị biến chất. Tuyệt đối không được sấy diêm sinh vì sẽ biến chất, mất vị ngọt, trong sẽ bạc, ngoài sẽ hồng."),
("Cầu Kỳ Tử",
    "Cây nhỏ, mọc đứng thành bụi sum sê, cao 0,5 - 1m. Cành cứng. đôi khi có gai ngắn ở kẽ lá. Lá nguyên mọc so le hoặc tụ tập 4 -5 cái, hình mũi mác, mặt trên màu lục sẫm bóng, mặt dưới nhạt; cuống lá ngắn. Hoa nhỏ, mọc đơn độc hoặc 2 - 3 cái ở kẽ lá, màu tím nhạt hoặc tím đỏ. Quả mọng, hình trứng, khi chín màu đỏ sẫm hoặc vàng đỏ, hạt nhiều. Ra hoa từ tháng 6-9, có quả từ tháng 7-10. Ngoài ra còn có loài câu kỷ quả tím đen (Lycium ruthenicum Murray) cũng được dùng.", 
        "Quả khô Câu kỷ tử hình bầu dục dài khoảng 0,5-1cm, đường kính khoảng hơn 0,2cm. Vỏ quả màu tím đỏ hoặc đỏ tươi, mặt ngoài nhăn teo, bên trong có nhiều hạt hình tạng thận màu vàng, có một đầu có vết của cuống quả. Không mùi, vị ngọt hơi chua, sau khi nếm nước bọt có màu vàng hồng.",
            "Vị ngọt, tính bình.",
                "Thuốc bổ, chữa ho lao, đau lưng mỏi gối, di tinh, mắt ra nhiều nước, mắt mờ, tiểu đường.",
                    "Ngày dùng 4 - 10g, dạng thuốc sắc hay ngâm rượu.",
                        "Đựng vào lọ kín để nơi khô ráo, nếu bị thâm đen đem xông diêm sinh hoặc phun rượu, xóc lên sẽ trở lại màu đỏ đẹp."),
("Đỗ Trọng",
    "Cây nhỡ hay cây to cao 10m hay hơn. Vỏ thân và lá có nhựa mủ trắng, vỏ màu xám, khi bẻ đôi sẽ thấy những sợi nhựa trắng mảnh như tơ nối giữa các mảnh vỏ. Lá mọc so le, hình trứng rộng, dài 6-8cm, rộng 3-7,5cm, màu lục bóng, mép khía răng. Lá cũng có gôm tựa gutta percha như ở vỏ. Hoa đơn tính khác gốc; hoa đực và hoa cái không có bao hoa; hoa đực mọc thành chùm; hoa cái tụ tập 5-10 cái ở nách lá. Quả hình thoi dẹt, màu nâu. Hoa tháng 3-5; quả tháng 7-9.", 
        "Từng tấm phẳng hoặc hai bên mép hơi cong vào, to nhỏ không đều, dày 0,2 - 0,5 cm. Mặt ngoài màu nâu nhạt hoặc màu hạt dẻ, có nhiều nếp nhăn dọc và vết tích của cành con. Loại vỏ mỏng (bóc ở cây ít năm) không cạo bỏ bớt vỏ thô bên ngoài có thể thấy rõ bì khổng. Mặt trong vỏ màu tím sẫm, trơn, chất giòn, dễ bẻ gẫy, mặt bẻ có nhiều sợi màu trắng bạc, có tính đàn hồi như cao su. Vị hơi đắng.",
            "Vị ngọt, hơi cay, tính ôn.",
                "Hạ áp, hạ cholesterol, giãn mạch, kháng viêm, chống co giật, giảm đau, cầm máu, lợi tiểu. Ôn thận, tráng dương, mạnh gân cốt, an thai, nhuận can táo, bổ can hư.",
                    "10 - 15g dạng thuốc sắc, ngâm rượu hay cao lỏng.",
                        ""),
("Hồng Táo", 
    "Là cây vừa hoặc cao, có thể cao đến 10m. Lá mọc so le, lá kèm thường biến thành gai, cuống ngắn 0,5-1cm, phiến lá hình trứng dài 3-7cm, rộng 2-3,5cm, mép có răng cưa thô, trên mặt rõ 3 gân chính, gân phụ cũng nổi rõ. Hoa nhỏ, mọc thành tán ở kẽ lá, mỗi tán gồm 7-8 hoa. Cánh hoa mầu vàng, xanh nhạt. Quả hình cầu hoặc hình trứng, khi còn xanh mầu nâu nhạt hoặc xanh nhạt, khi chín mầu đỏ sẫm. Mùa hoa tháng 4-5, mùa quả tháng 7-9. Hiện nay ở miền Bắc nước ta, cây đã được đem trồng nhiều nơi, đang phát triển mạnh, phổ biển trồng bằng chiết cành vào mùa xuân.", 
        "Quả khô hình viên chùy, dài chừng 18mm - 32mm, thô chừng 15 - 18mm. Bên ngoài có màu đỏ nâu hoặc nâu tím. Có trái có vết nhăn nheo rất sâu, cuối quả có lõm vào, có vết cuống quả hoặc vết sẹo hình tròn. Chất mềm mà nhẹ, bên ngoài vỏ quả mỏng, nhăn rúm, chất thịt màu nâu nhạt, có dầu dẻo. Hạt quả hai đầu nhọn, vỏ cứng, đập ra có nhân cứng màu trắng.",
            "Vị ngọt, tính bình.",
                "Chữa lo âu, mất ngủ, tỳ vị hư nhược.",
                    "Ngày 10 - 30g (3 - 10 quả), thường phối hợp trong các bài thuốc bổ, sắc hoặc ngâm rượu uống.",
                        "Đậy kín, tránh sâu bọ, chuột, gián."),
("Trạch Tả", 
    "Loại thảo mọc ở ao và ruộng, cao 0,2-1m. Thân rễ trắng hình cầu hay hình con quay, thành cụm, lá mọc ở gốc, hình trứng thuôn hay lưỡi mác, phía cuống hơi hẹp lại. Cán hoa mang ở đỉnh nhiều vòng hoa có cuống dài. Hoa họp thành tán, đều, lưỡng tính, 3 lá đài màu lục, 3 cánh hoa trắng hay hơi hồng, 6 nhị, nhiều tâm bì rời nhau, xếp xoắn ốc. Quả bé. Cây Trạch tả mọc hoang ở những nơi ẩm ướt ở Sapa, Điện Biên, Cao Bằng, Lạng Sơn.",
        "Hình cầu tròn, hình bầu dục hoặc hình tròn trứng, dài 3,3cm-6,6cm, đường kính 3-5cm. Vỏ thô, mặt ngoài mầu trắng vàng, có vằn rãnh nông quanh ngang củ, rải rác có nhiều vết tơ lồi nhỏ hoặc có lồi sẹo bướu. Chất cứng, mặt gẫy mầu trắng vàng, có bột, nhiều lỗ nhỏ. Mùi hơi nhẹ, vị hơi đắng.", 
            "Vị ngọt, tính hàn.",
                "Lợi thấp nhiệt, tiết hoả tà, lợi tiểu.",
                    "Ngày dùng 8 – 16g",
                        "Để nơi khô ráo vì dễ mốc mọt, sấy xong để trong hòm kín. Có thể sấy hơi diêm sinh.");
